### ISSUE TITLE
Config file preview doesn't contain longer strings

### ISSUE THREAD

**Issue by scallaway** [tommilligan/qvet#13]
![image](https://user-images.githubusercontent.com/16577635/226650348-1e2baf94-67f8-46dc-9ac5-9f4fa1587eb5.png)

As per the screenshot, there's an X-axis overflow, but the background doesn't seem to support that.

I think either have a hard-wrap, or make the background extend (the latter probably being a slightly nicer experience).

**Comment by tommilligan** [comment]
Nice spot - have updated to add a wrap. Now deployed
